/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    String user, name;
    int chucVu;

    public Main(String user, int chucVu, String name) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        Border border = BorderFactory.createLineBorder(Color.GRAY, 3);

        this.user = user;
        this.name = name;
        this.chucVu = chucVu;
        lbl_NameNV.setText(name);
    }

    private Main() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_NameNV = new javax.swing.JLabel();
        lbl_GuiXe = new javax.swing.JLabel();
        lbl_Xe = new javax.swing.JLabel();
        lbl_NhanVien = new javax.swing.JLabel();
        lbl_ThongKe = new javax.swing.JLabel();
        lbl_DangXuat = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phầm mềm gửi xe CarPankPoLy\n");
        setBackground(new java.awt.Color(153, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, java.awt.Color.gray));

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.red));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-car-park-50.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 153, 255));
        jLabel2.setText("CAR PARK POLY");

        lbl_NameNV.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_NameNV.setForeground(java.awt.Color.red);
        lbl_NameNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_NameNV.setText("Nguyễn Văn A");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(51, 51, 51))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(lbl_NameNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lbl_NameNV)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        lbl_GuiXe.setBackground(java.awt.Color.lightGray);
        lbl_GuiXe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_GuiXe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_GuiXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-parking-24.png"))); // NOI18N
        lbl_GuiXe.setText("GỬI XE");
        lbl_GuiXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_GuiXeMouseClicked(evt);
            }
        });

        lbl_Xe.setBackground(new java.awt.Color(255, 51, 51));
        lbl_Xe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Xe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Xe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-car-24.png"))); // NOI18N
        lbl_Xe.setText("XE");
        lbl_Xe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_XeMouseClicked(evt);
            }
        });

        lbl_NhanVien.setBackground(new java.awt.Color(255, 51, 51));
        lbl_NhanVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_NhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-staff-24.png"))); // NOI18N
        lbl_NhanVien.setText("Nhân Viên");
        lbl_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_NhanVienMouseClicked(evt);
            }
        });

        lbl_ThongKe.setBackground(new java.awt.Color(255, 51, 51));
        lbl_ThongKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_ThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-analytics-24.png"))); // NOI18N
        lbl_ThongKe.setText("Thống Kê");
        lbl_ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ThongKeMouseClicked(evt);
            }
        });

        lbl_DangXuat.setBackground(new java.awt.Color(255, 51, 51));
        lbl_DangXuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_DangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_DangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-export-24.png"))); // NOI18N
        lbl_DangXuat.setText("Đăng Xuất");
        lbl_DangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_DangXuatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_GuiXe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_Xe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_ThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_DangXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_GuiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Xe, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_ThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 419));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/taxi-cong-nghe-gia-re-nhung-thua-khach-o-san-bay-tan-son-nhat-1.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, java.awt.Color.gray));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 420));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 0, 640, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_DangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_DangXuatMouseClicked
        // Đăng xuất 
        setBackgroundJlabel(lbl_DangXuat);
        resetBackgroundJlabel(lbl_GuiXe);
        resetBackgroundJlabel(lbl_NhanVien);
        resetBackgroundJlabel(lbl_ThongKe);
        resetBackgroundJlabel(lbl_Xe);
        int choice = JOptionPane.showConfirmDialog(null, "Bạn có muốn đăng xuất không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            // Xử lý khi người dùng chọn "Có"
            JOptionPane.showMessageDialog(this, "Đăng xuất thành công ! ");
            new LoginView().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_lbl_DangXuatMouseClicked

    private void lbl_GuiXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_GuiXeMouseClicked
        // Gửi xe 
        setBackgroundJlabel(lbl_GuiXe);
        resetBackgroundJlabel(lbl_Xe);
        resetBackgroundJlabel(lbl_NhanVien);
        resetBackgroundJlabel(lbl_ThongKe);
        resetBackgroundJlabel(lbl_DangXuat);

    }//GEN-LAST:event_lbl_GuiXeMouseClicked

    private void lbl_XeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_XeMouseClicked
        // Xe 
        setBackgroundJlabel(lbl_Xe);
        resetBackgroundJlabel(lbl_GuiXe);
        resetBackgroundJlabel(lbl_NhanVien);
        resetBackgroundJlabel(lbl_ThongKe);
        resetBackgroundJlabel(lbl_DangXuat);
    }//GEN-LAST:event_lbl_XeMouseClicked

    private void lbl_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhanVienMouseClicked
        // Nhân viên 
        setBackgroundJlabel(lbl_NhanVien);
        resetBackgroundJlabel(lbl_GuiXe);
        resetBackgroundJlabel(lbl_Xe);
        resetBackgroundJlabel(lbl_ThongKe);
        resetBackgroundJlabel(lbl_DangXuat);
    }//GEN-LAST:event_lbl_NhanVienMouseClicked

    private void lbl_ThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ThongKeMouseClicked
        // Thống kê 
        setBackgroundJlabel(lbl_ThongKe);
        resetBackgroundJlabel(lbl_GuiXe);
        resetBackgroundJlabel(lbl_NhanVien);
        resetBackgroundJlabel(lbl_Xe);
        resetBackgroundJlabel(lbl_DangXuat);
    }//GEN-LAST:event_lbl_ThongKeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_DangXuat;
    private javax.swing.JLabel lbl_GuiXe;
    private javax.swing.JLabel lbl_NameNV;
    private javax.swing.JLabel lbl_NhanVien;
    private javax.swing.JLabel lbl_ThongKe;
    private javax.swing.JLabel lbl_Xe;
    // End of variables declaration//GEN-END:variables

    public void setBackgroundJlabel(JLabel jLabel) {
        jLabel.setBackground(new Color(220,220,220));
        jLabel.setOpaque(true);
    }

    public void resetBackgroundJlabel(JLabel jLabel) {
        jLabel.setBackground(Color.WHITE);
    }
}
